services:
  jupyter:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8889:8888
    volumes:
      - jupyter-data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='TokenChangeMe'

volumes:
  jupyter-data:
    name: jupyter-data
